// <auto-generated />
namespace JackstimetableService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class CountriesandCitiesadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CountriesandCitiesadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201504131852037_Countries and Cities added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
